"""
Django settings for HealthPoint project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-solo-para-desarrollo-local")

# SECURITY WARNING: don't run with debug turned on in production!
# Por defecto queda activo para desarrollo local. En un servidor se define
# DJANGO_DEBUG=False y la lista de dominios en DJANGO_ALLOWED_HOSTS.
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',    #aplicación de administración
    'django.contrib.auth',     #aplicación de autenticación
    'django.contrib.contenttypes',  #aplicación de tipos de contenido
    'django.contrib.sessions',  #aplicación de sesiones
    'django.contrib.messages',  #aplicación de mensajes
    'django.contrib.staticfiles',  #aplicación de archivos estáticos
    'core',  # asegúrate de que esté aquí 
]

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'core' / 'static']

# === Autenticación ===
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'      # realmente no se usará mucho porque redirigimos a mano
LOGOUT_REDIRECT_URL = '/login/'

MIDDLEWARE = [  #Los middlewares son componentes que procesan las solicitudes y respuestas en Django
    'django.middleware.security.SecurityMiddleware', #seguridad de la aplicación
    'django.contrib.sessions.middleware.SessionMiddleware', #gestión de sesiones
    'django.middleware.common.CommonMiddleware',    #funciones comunes de middleware
    'django.middleware.csrf.CsrfViewMiddleware',   #protección contra ataques CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware',  #gestión de autenticación
    'django.contrib.messages.middleware.MessageMiddleware',  #gestión de mensajes
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  #protección contra clickjacking
]

ROOT_URLCONF = 'HealthPoint.urls'

TEMPLATES = [{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [BASE_DIR / 'core' / 'templates'],
    'APP_DIRS': True,
    'OPTIONS': {'context_processors': [
        'django.template.context_processors.debug', #procesador de contexto de depuración
        'django.template.context_processors.request', #procesador de contexto de solicitud
        'django.contrib.auth.context_processors.auth', #procesador de contexto de autenticación
        'django.contrib.messages.context_processors.messages', #procesador de contexto de mensajes
    ]},
}]



WSGI_APPLICATION = 'HealthPoint.wsgi.application'   #wsgi es la interfaz entre el servidor web y la aplicación Django
#wsgi funciona como un puente que permite que el servidor web maneje las solicitudes y respuestas de la aplicación Django de manera eficiente.

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'  #código de idioma

TIME_ZONE = 'America/Santiago'   #zona horaria

USE_I18N = True     #habilitar la internacionalización

USE_TZ = True    #habilitar el soporte de zonas horarias



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
