# Generated by Django 5.2.7 on 2025-10-13 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('responsable', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('unidad', models.CharField(max_length=20)),
                ('stock_inicial', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimiento', to='core.box')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimiento', to='core.insumo')),
            ],
        ),
    ]
