# Generated by Django 5.2.7 on 2025-11-26 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

#Creado la migración para agregar los campos stock_minimo y usuario
class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0, help_text='Nivel mínimo recomendado para generar alerta'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to=settings.AUTH_USER_MODEL),
        ),
    ]
