# Generated by Django 5.2.7 on 2025-11-27 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

#creado la migración para modificar el campo usuario en Movimiento
class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_insumo_stock_minimo_movimiento_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to=settings.AUTH_USER_MODEL),
        ),
    ]
